; ============================================================
;  Banc de mesure de force — OpenRB-150 (SAMD21G18A)
;  PlatformIO configuration
; ============================================================
[env:openrb-150]
platform  = atmelsam
board     = openrb-150
framework = arduino
upload_speed = 1200
; Vitesse série monitor
monitor_speed = 115200
monitor_dtr   = 0       ; empêche le monitor de reset la board à l'ouverture
monitor_rts   = 0

; Librairies Dynamixel (ROBOTIS)
lib_deps =
    https://github.com/ROBOTIS-GIT/Dynamixel2Arduino.git

; Build flags
build_flags =
    -DDYNAMIXEL_SERIAL=Serial1
    -DARDUINO_SAMD_OPENRB
