; ============================================================
;  Debug sniffer — Arduino Uno
; ============================================================
[env:uno]
platform     = atmelavr
board        = uno
framework    = arduino
monitor_speed = 115200
