; ============================================================
;  Banc de mesure de force — LoLin NodeMCU v3 (ESP8266)
;  PlatformIO configuration
; ============================================================
[env:nodemcuv2]
platform  = espressif8266
board     = nodemcuv2
framework = arduino

; Vitesse série monitor
monitor_speed = 115200

; Librairies
lib_deps =
    links2004/WebSockets @ ^2.4.0
    bblanchon/ArduinoJson @ ^7.0.0

; Build flags optionnels
build_flags =
    -DCORE_DEBUG_LEVEL=0
